config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets, only: %i[index show new create edit update destroy] do
    resources :foods, only: %i[index new create]
    resources :allergies, only: %i[index new create]
    resources :professionals, only: %i[index new create]
    resources :diseases, only: %i[index new create]
    resources :medications, only: %i[index new create]
    resources :vaccines, only: %i[index new create]
    resources :services, only: %i[index]
  end

  resources :foods, only: %i[edit update destroy]
  resources :allergies, only: %i[edit update destroy]
  resources :services, only: %i[edit update destroy]
  resources :diseases, only: %i[edit update destroy]
  resources :medications, only: %i[edit update destroy]
  resources :vaccines, only: %i[edit update destroy]
  resources :professional, only: %i[edit update destroy] do
    resources :services, only: %i[new create]
  end

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :foods, dependent: :destroy
  has_many :medications, dependent: :destroy
  has_many :vaccines, dependent: :destroy
  has_many :allergies, dependent: :destroy
  has_many :diseases, dependent: :destroy
  has_many :professionals, dependent: :destroy
  has_many :services, through: :professionals

  validates :name, :species, :age, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pets, only: %i[edit update show destroy]

  def index
    #  show only the pets from the current user
    @pets = current_user.pets
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    # Give a user for the pet
    @pet.user = current_user
    # redirect to the show page of the pet if it is saved
    if @pet.save
      redirect_to pet_path(@pet), notice: 'Pet was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :breed, :gender, :clothes_size, :walk, :adopted, :arrival_date, :weight, :sterilized)
  end

  def set_pets
    @pet = Pet.find(params[:id])
  end

end

app/views/pets/edit.html.erb
<h1>Here I have all my pet infos</h1>

<hr>
<p>Nome: <%= @pet.name %></p>
<p>Raça: <%= @pet.breed %></p>
<p>Espécie: <%= @pet.species %></p>
<p>Idade: <%= @pet.age %></p>
<p>Gênero: <%= @pet.gender %></p>
<p>Roupa: <%= @pet.clothes_size %></p>
<p>Quantas caminhadas por dia: <%= @pet.walk %></p>
<p>Foi adotado?: <%= @pet.adopted %></p>
<p>Aniversário (nascimento ou adoção): <%= @pet.arrival_date %></p>
<p>Peso: <%= @pet.weight %></p>
<p>Foi castrado?: <%= @pet.sterilized %></p>
<p>Owner: <%= @pet.user.email %></p>
<hr>

<h1>Here is the form to edit the Pet</h1>
<%# TODO -> Colocar as infos com JS para editar o que quiser na mesma hora, sem usar o FORM %>
<div>
  <br>
      <%= simple_form_for @pet do |f| %>
      <%= f.input :name, :label => 'Nome' %>
      <%= f.input :age, as: :integer, :label => 'Idade'  %>
      <%= f.input :species, collection: ['Cachorro', 'Gato', 'Outro'], :label => 'Espécie' %>
      <%= f.input :breed, :label => 'Raça' %>
      <%= f.input :gender, :label => 'Gênero' %>
      <%= f.input :clothes_size, :label => 'Tamanho da Roupa' %>
      <%= f.input :walk, as: :integer, :label => 'Quantas caminhadas por dia?' %>
      <%= f.input :adopted, as: :boolean, :label => 'Adotado' %>
      <%= f.input :arrival_date, as: :date, :label => 'Aniversário / Data que cheguei em casa' %>
      <%= f.input :weight, as: :float, :label => 'Peso' %>
      <%= f.input :sterilized, as: :boolean, :label => 'Castrado' %>

      <%= f.button :submit, "Edit this pet" %>

    <% end %>

      <%= link_to "Go back to the Pet Show",  pet_path(@pet) %>
</div>

app/views/pets/index.html.erb
<h1>All Pets here!</h1>
<% @pets.each do |pet| %>
  <%= link_to  pet_path(pet) do %>
    <p><%= pet.name %></p>
  <% end %>
<% end %>


<%= link_to "Add a pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>Here we have the form to create a new pet</h1>

<div>
  <br>
    <%= simple_form_for @pet do |f| %>
      <%= f.input :name, :label => 'Nome' %>
      <%= f.input :age, as: :integer, :label => 'Idade'  %>
      <%= f.input :species, collection: ['Cachorro', 'Gato', 'Outro'], :label => 'Espécie' %>
      <%= f.input :breed, :label => 'Raça' %>
      <%= f.input :gender, :label => 'Gênero' %>
      <%= f.input :clothes_size, :label => 'Tamanho da Roupa' %>
      <%= f.input :walk, as: :integer, :label => 'Quantas caminhadas por dia?' %>
      <%= f.input :adopted, as: :boolean, :label => 'Adotado' %>
      <%= f.input :arrival_date, as: :date, :label => 'Aniversário / Data que cheguei em casa' %>
      <%= f.input :weight, as: :float, :label => 'Peso' %>
      <%= f.input :sterilized, as: :boolean, :label => 'Castrado' %>

      <%= f.button :submit, "Add this pet" %>

    <% end %>

  
</div>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h2>My own pet and notifications here</h2>

<%= link_to edit_pet_path(@pet) do %>
<p>Edit <%= @pet.name %></p>
<% end %>

<%= link_to "Delete this pet", pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this pet?" } %>
<br>
<br>
<%= link_to "See all pets", pets_path %>
<br>
<br>
<%= link_to "See Foods", pet_foods_path(@pet) %>
<br>
<br>
<%= link_to "See allergies", pet_allergies_path(@pet) %>
<br>
<br>
<%= link_to "See Professionals", pet_professionals_path(@pet) %>
<br>
<br>
<%= link_to "See Services", pet_services_path(@pet) %>
<br>
<br>
<%= link_to "See diseases", pet_diseases_path(@pet) %>
<br>
<br>
<%= link_to "See medications", pet_medications_path(@pet) %>
<br>
<br>
<%= link_to "See vaccines", pet_vaccines_path(@pet) %>