config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets, only: %i[index show new create edit update destroy] do
    resources :foods, only: %i[index new create]
    resources :allergies, only: %i[index new create]
    resources :professionals, only: %i[index new create]
    resources :diseases, only: %i[index new create]
    resources :medications, only: %i[index new create]
    resources :vaccines, only: %i[index new create]
    resources :services, only: %i[index]
  end

  resources :foods, only: %i[edit update destroy]
  resources :allergies, only: %i[edit update destroy]
  resources :services, only: %i[edit update destroy]
  resources :diseases, only: %i[edit update destroy]
  resources :medications, only: %i[edit update destroy]
  resources :vaccines, only: %i[edit update destroy]
  resources :professional, only: %i[edit update destroy] do
    resources :services, only: %i[new create]
  end

end

app/models/vaccine.rb
class Vaccine < ApplicationRecord
  belongs_to :pet

  validates :name, :administration_date, presence: true
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  before_action :set_pet, only: %i[index new create]
  before_action :set_vaccine, only: %i[edit update destroy]

  def index
    @vaccines = @pet.vaccines
  end

  def new
    @vaccine = Vaccine.new
  end

  def create
    @vaccine = Vaccine.new(vaccine_params)

    # give the pet to the vaccine
    @vaccine.pet = @pet

    # redirect to the vaccines page if it saves
    if @vaccine.save
      redirect_to pet_vaccines_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @vaccine.update(vaccine_params)
    redirect_to pet_vaccines_path(@vaccine.pet)
  end

  def destroy
    @vaccine.destroy
    redirect_to pet_vaccines_path(@vaccine.pet)
  end

  private

  def vaccine_params
    params.require(:vaccine).permit(:name, :purpose_vaccine, :administration_date, :frequency, :comment)
  end

  def set_vaccine
    @vaccine = Vaccine.find(params[:id])
  end

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

end

app/views/vaccines/edit.html.erb
<h1>Edite a vacina</h1>

<%= simple_form_for [@pet, @vaccine] do |f| %>
  <%= f.input :name, :label => 'Nome' %>
  <%= f.input :purpose_vaccine, :label => 'Finalidade da Vacina' %>
  <%= f.input :administration_date, :label => 'Data de Administração' %>
  <%= f.input :frequency, :label => 'Frequência' %>
  <%= f.input :comment, :label => 'Comentário' %>
  <%= f.button :submit, 'Adiciona essa vacina' %>
<% end %>

app/views/vaccines/index.html.erb
<h1>Veja todas as vacinas</h1>

<% @vaccines.each do |vaccine| %>
  <h3><%= vaccine.name %></h3>
  <p>Finalidade: <%= vaccine.purpose_vaccine %></p>
  <p>Data de administração: <%= vaccine.administration_date %></p>
  <p>Com que frequência tomar (anos): <%= vaccine.frequency %></p>
  <p>Comentário: <%= vaccine.comment %></p>

  <%= link_to "Editar essa vacina", edit_vaccine_path(vaccine) %>
  <br>
  <%= link_to vaccine_path(vaccine), data: { turbo_method: :delete, turbo_confirm: "Tem certeza que deseja deletar essa vacina?"} do %>
    <i class="fa-solid fa-trash"></i>
  <% end %>

  <hr>
<% end %>

<%= link_to 'Adicione uma nova vacina', new_pet_vaccine_path %>
<br>

<%= link_to "Voltar para a o Show do Pet", pet_path(@pet) %>

app/views/vaccines/new.html.erb
<h1>Formulário para adicionar uma nova vacina</h1>

<%= simple_form_for [@pet, @vaccine] do |f| %>
  <%= f.input :name, :label => 'Nome' %>
  <%= f.input :purpose_vaccine, :label => 'Finalidade da Vacina' %>
  <%= f.input :administration_date, :label => 'Data de Administração' %>
  <%= f.input :frequency, :label => 'Frequência' %>
  <%= f.input :comment, :label => 'Comentário' %>
  <%= f.button :submit, 'Adiciona essa vacina' %>
<% end %>

<%= link_to "Voltar para todas as vacinas", pet_vaccines_path(@pet) %>