config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets, only: %i[index show new create edit update destroy] do
    resources :foods, only: %i[index new create]
    resources :allergies, only: %i[index new create]
    resources :professionals, only: %i[index new create]
    resources :diseases, only: %i[index new create]
    resources :medications, only: %i[index new create]
    resources :vaccines, only: %i[index new create]
    resources :services, only: %i[index]
  end

  resources :foods, only: %i[edit update destroy]
  resources :allergies, only: %i[edit update destroy]
  resources :services, only: %i[edit update destroy]
  resources :diseases, only: %i[edit update destroy]
  resources :medications, only: %i[edit update destroy]
  resources :vaccines, only: %i[edit update destroy]
  resources :professional, only: %i[edit update destroy] do
    resources :services, only: %i[new create]
  end

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :pet

  validates :name, :category, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_pets, only: %i[index new create]
  before_action :set_food, only: %i[edit update destroy]

  def index
    @foods = @pet.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    # Give the pet to the food
    @food.pet = @pet
    # Redirect to the Foods page if it saves
    if @food.save
      redirect_to pet_foods_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @food.update(food_params)
    redirect_to pet_foods_path(@food.pet)
  end

  def destroy
    @food.destroy
    redirect_to pet_foods_path(@food.pet)
  end

  private

  def food_params
    params.require(:food).permit(:name, :category, :price, :purchase_date)
  end

  def set_food
    @food = Food.find(params[:id])
  end

  def set_pets
    @pet = Pet.find(params[:pet_id])
  end
end

app/views/foods/edit.html.erb
<h1>Edit the food</h1>

<div>
  <br>
      <%= simple_form_for [@pet, @food] do |f| %>
      <%= f.input :name, :label => 'Nome' %>
      <%= f.input :category, :label => 'Ração ou Petisco' %>
      <%= f.button :submit, "Edit this food" %>
    <% end %>

app/views/foods/index.html.erb
<h1>Here we can see the history of ALL foods</h1>
<% @foods.each do |food| %>
<h5><%= food.category %></h5>
  <p><%= food.name %></p>
  <%= link_to "Edit the food", edit_food_path(food) %>
  <br>
  <%= link_to "Delete this food", food_path(food), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this food?" } %>
<br>
  <hr>
<% end %>

<%= link_to "Add a new food",  new_pet_food_path(@pet) %>
<br>
<%= link_to "Go back to the Pet Show",  pet_path(@pet) %>

app/views/foods/new.html.erb
<h1>Form to create new food</h1>

<div>
  <br>
      <%= simple_form_for [@pet, @food] do |f| %>
      <%= f.input :name, :label => 'Nome' %>
      <%= f.input :category, collection: ['Ração', 'Petisco', 'Outro'], :label => 'Ração ou Petisco' %>
      <%= f.button :submit, "Add this food to your pet" %>
    <% end %>
</div>