config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets, only: %i[index show new create edit update destroy] do
    resources :foods, only: %i[index new create]
    resources :allergies, only: %i[index new create]
    resources :professionals, only: %i[index new create]
    resources :diseases, only: %i[index new create]
    resources :medications, only: %i[index new create]
    resources :vaccines, only: %i[index new create]
    resources :services, only: %i[index]
  end

  resources :foods, only: %i[edit update destroy]
  resources :allergies, only: %i[edit update destroy]
  resources :services, only: %i[edit update destroy]
  resources :diseases, only: %i[edit update destroy]
  resources :medications, only: %i[edit update destroy]
  resources :vaccines, only: %i[edit update destroy]
  resources :professional, only: %i[edit update destroy] do
    resources :services, only: %i[new create]
  end

end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to :pet

  validates :name, presence: true
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  before_action :set_pet, only: %i[index new create]
  before_action :set_allergy, only: %i[edit update destroy]

  def index
    @allergies = @pet.allergies
  end

  def new
    @allergy = Allergy.new
  end

  def create
    @allergy = Allergy.new(allergy_params)

    # give the pet to the allergy
    @allergy.pet = @pet

    # redirect to the allergies page if it saves
    if @allergy.save
      redirect_to pet_allergies_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @allergy.update(allergy_params)
    redirect_to pet_allergies_path(@allergy.pet)
  end

  def destroy
    @allergy.destroy

    redirect_to pet_allergies_path(@allergy.pet)
  end

  private

  def allergy_params
    params.require(:allergy).permit(:name, :comment)
  end

  def set_allergy
    @allergy = Allergy.find(params[:id])
  end

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

end

app/views/allergies/edit.html.erb
<h1>Update here your allergy</h1>

<%= simple_form_for [@pet, @allergy] do |f| %>
  <%= f.input :name, :label => 'Nome' %>
  <%= f.input :comment, :label => 'Comentário' %>
  <%= f.button :submit, "Edit this allergy" %>
<% end %>

app/views/allergies/index.html.erb
<h1>My allergies</h1>

<% @allergies.each do |allergy| %>
  <h2><%= allergy.name %></h2>
  <p><%= allergy.comment %></p>

  <%= link_to "Edite essa alergia", edit_allergy_path(allergy) %>
  <br>

  <%= link_to allergy_path(allergy), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this allergy?"} do %>
    <i class="fa-solid fa-trash"></i>
  <% end %>

  <hr>

<% end %>

<%= link_to "Adiciona uma alergia", new_pet_allergy_path(@pet) %>
<br>

<%= link_to "Go back to the Pet Show", pet_path(@pet) %>

app/views/allergies/new.html.erb
<h1>Add a new allergy</h1>

<%= simple_form_for [@pet, @allergy] do |f| %>
  <%= f.input :name, :label => 'Nome' %>
  <%= f.input :comment, :label => 'Comentário' %>
  <%= f.button :submit, "Add this allergy" %>
<% end %>